### ISSUE TITLE
The domain has expired, is this project still being maintained?

### ISSUE THREAD

**Issue by JesseTG** [qt-pods/qt-pods-website#2]
[The domain has expired.](http://www.qt-pods.org/)  If QtPods is no longer being maintained, can you put out a statement or something so I can take it off of [awesome-qt](https://github.com/JesseTG/awesome-qt)?

**Comment by jacob3141** [comment]
@JesseTG Can you just link to the github page of qt-pods? This project is still alive and working, but few people have been interested so far. The website was causing unnecessary costs so I cancelled it, as noone was really interested.

**Comment by jacob3141** [comment]
Also, the pod master source has changed to http://omg-it.works/pods.json. I will add a line to the README.

**Comment by JesseTG** [comment]
Okay, you got it.

**Comment by JesseTG** [comment]
Also, have you considered at least keeping up the site on GitHub Pages?  It's totally free, and you already have the website.
